name: test
# either manually started, or after spinalhdl runs
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["spinalhdl"]
    branches: [main]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Download - spinalhdl-generated
      uses: actions/download-artifact@v3
      with:
        name: spinalhdl-generated
        path: spinalhdl-generated/

    - name: Prepare - spinalhdl-generated
      shell: bash
      run: |
        cp -av spinalhdl-generated/*.v src/

    # install oss fpga tools
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
          python-override: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: | 
        yosys --version
        iverilog -V
        cocotb-config --libpython
        cocotb-config --python-bin

    - name: test
      run: |
        cd src
        make clean
        make
        # make will return success even if the test fails, so check for failure in the results.xml
        ! grep failure results.xml

    - name: upload vcd
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
          name: test-vcd
          path: src/tb.vcd

